version: ~> 1.0

env:
  global:
    - secure: "i/pZoUGqELaC/usFq/coVPkA+jE/OUP+PxswsGUQqX8HthlIxSEmbT1fCxb0euHqLH1OpxqCflAgVBkF3cqEQbcleMUrfGwdnbo6Ab7vVYcvWTmAcEjA01xP1+0f4plfEhlLQR1/ekkeZA2PYOC3Zx3NUfDEEjvKpHxSu3gg7gN0lS5q9+CdPzXF4t/2VCfzb/B9a13eW0rv0+qZlutEPzFu9CjO1/DLfmy92yh/kigZ/ZHHP0x9CDjEjvD3xMsiQbtwmybp92uyAkJBl73f+WolUKSBAeL5CnsCliBF2aVXc/hsN+HQk/vgcDHHLwiXs173QxtxPzZZaztEU8d6waIYrn/9qQkL3bYbAYxTzNlIHElHEWRwxwPpYOLQNe3trTzVPR5vZp0Wwaug68EA63K76exM4GCku7KKtO93wP9oyfhV67e16y1m2xchad582r7Ek4hy35HNgzUGlQOfAzcZaRxuW4wuza/Z4yZPhgKb6+Pg+cu/kza7t9K8HvQZhocc9mIIyloU42QVATLVV/4U+k2ghmZeVELFU+eUEca+KgAIcU8BjIWY7jZay8GOEX7/kogYc+d08tDqMwKEacrAgRD3XsMSghnUcwGRq9wDbtqUAffzvtyymw6mO8bdCrQG7d2MvPXeiwK2we7V0c0Cd6nmS8uFOJVbUcCnE38="

    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="docs-requirements.txt dev-requirements.txt requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="pcdsdevices"

    # The name of the conda package
    - CONDA_PACKAGE="pcdsdevices"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"
    # Extra dependencies needed to run the tests which are not included
    # at the recipe and dev-requirements.txt. E.g. PyQt
    - CONDA_EXTRAS="pip"
    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    # Extra dependencies needed to run the test with Pip (similar to
    # CONDA_EXTRAS) but for pip
    - PIP_EXTRAS="PyQt5 -e ./"

jobs:
  allow_failures:
    - name: "Python - PIP"

import:
  # This import enables a set of standard python jobs including:
  # - Build
  #   - Anaconda Package Build
  # - Tests
  #   - Python Linter
  #   - Package Linter
  #   - Documentation
  #   - Python - PIP based
  #   - Python 3.9 - Conda base
  # - Deploy
  #   - Documentation using doctr
  #   - Conda Package - uploaded to pcds-dev and pcds-tag
  #   - PyPI
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda-latest.yml
