{% set data = load_setup_py_data() %}

package:
  name: pcdsdevices
  version : {{ data.get('version') }}

source:
  path: ..

build:
  number: 1
  noarch: python

requirements:
  build:
    - python >=3.9
    - setuptools
  run:
    - python >=3.9
    - bluesky >=1.6.4
    - happi
    - jsonschema
    - matplotlib-base
    - numpy
    - ophyd >=1.5.1
    - pcdscalc >=0.2.0
    - pcdsutils >=0.4.0
    - pint
    - prettytable
    - pyepics >=3.4.2
    - pytmc >=2.7.0
    - pyyaml
    - schema
    - scipy
  run_constrained:
    - pmgr >=2.0.2

test:
  imports:
    - pcdsdevices

about:
  home: https://github.com/pcdshub/pcdsdevices
  license: SLAC Open License
  summary: IOC definitions for LCLS Beamline Devices
